### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by TheaperDeng** [TheaperDeng/git_learning#2]
- [x] Raise a PR (resolve issue #4 ) [Scenario 1,2]
- [ ] Rebase and fix the conflict [Scenario 3]
- [x] While doing it, change to resolve issue #5  (don't commit what you have just changed for readme.txt)
- [x] Change readme.txt and discard the change, solve issue #5  and raise PR.
- [ ] Only solve the mis spell for the issue #4
